name: Install Apache

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Apache
        run: |
          sudo yum install httpd -y

      - name: Start Apache
        run: |
          sudo systemctl start httpd
          sudo systemctl enable httpd

      - name: Copy index.html
        run: |
          sudo cp index.html /var/www/html/index.html

      - name: Verify Apache
        run: |
          systemctl status httpd --no-pager