name: My Second Workflow

on:
  push:

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display Date
        run: date

      - name: Display Directory
        run: pwd

      - name: Display Files
        run: ls -la