name: Deploy Website Using Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nginx
        run: |
          sudo yum install nginx -y

      - name: Start and Enable Nginx
        run: |
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Deploy Website
        run: |
          sudo cp index.html /usr/share/nginx/html/index.html

      - name: Verify Nginx Status
        run: |
          systemctl status nginx --no-pager